#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "conditional-expression.h"

namespace gliss {

namespace ast {

class array_specifier_conditional_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  array_specifier_conditional_t(
    const token_t &,
    const conditional_expression_t &,
    const token_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // array_specifier_conditional_t

const std::vector<std::vector<any_pattern_item_t>> array_specifier_conditional_t::patterns = {
  {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("LEFT_BRACKET")),
    pattern_item_t<conditional_expression_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("RIGHT_BRACKET"))
  }
};

}   // ast

}   // gliss
