#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "expression.h"

namespace gliss {

namespace ast {

class case_label_t: public ast_t {

public:

  using unique_pattern_t = std::shared_ptr<any_pattern_item_t>;

  using pattern_t = std::vector<unique_pattern_t>;

  static const std::vector<pattern_t> patterns;

  case_label_t(
    const token_t &,
    const expression_t &,
    const token_t &
  );

  case_label_t(
    const token_t &,
    const token_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // case_label_t

const std::vector<case_label_t::pattern_t> case_label_t::patterns = {
  {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("CASE")),
    pattern_item_t<expression_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("COLON"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("DEFAULT")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("COLON"))
  }
};

}   // ast

}   // gliss
