#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "compound-statement-no-new-scope-list.h"

namespace gliss {

namespace ast {

class compound_statement_no_new_scope_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  compound_statement_no_new_scope_t(
    const token_t &,
    const token_t &
  );

  compound_statement_no_new_scope_t(
    const compound_statement_no_new_scope_list_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // compound_statement_no_new_scope_t

const std::vector<std::vector<any_pattern_item_t>> compound_statement_no_new_scope_t::patterns = {
  {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("LEFT_BRACE")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("RIGHT_BRACE"))
  }, {
    pattern_item_t<compound_statement_no_new_scope_list_t>::get()
  }
};

}   // ast

}   // gliss
