#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "condition.h"

namespace gliss {

namespace ast {

class conditionopt_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  conditionopt_t(
    const condition_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // conditionopt_t

const std::vector<std::vector<any_pattern_item_t>> conditionopt_t::patterns = {
  {
    pattern_item_t<condition_t>::get()
  }
};

}   // ast

}   // gliss
