#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "conditional-expression.h"

namespace gliss {

namespace ast {

class constant_expression_t: public ast_t {

public:

  using unique_pattern_t = std::shared_ptr<any_pattern_item_t>;

  using pattern_t = std::vector<unique_pattern_t>;

  static const std::vector<pattern_t> patterns;

  constant_expression_t(
    const conditional_expression_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // constant_expression_t

const std::vector<constant_expression_t::pattern_t> constant_expression_t::patterns = {
  {
    pattern_item_t<conditional_expression_t>::get()
  }
};

}   // ast

}   // gliss
