#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "declaration.h"

namespace gliss {

namespace ast {

class declaration_statement_t: public ast_t {

public:

  using unique_pattern_t = std::shared_ptr<any_pattern_item_t>;

  using pattern_t = std::vector<unique_pattern_t>;

  static const std::vector<pattern_t> patterns;

  declaration_statement_t(
    const declaration_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // declaration_statement_t

const std::vector<declaration_statement_t::pattern_t> declaration_statement_t::patterns = {
  {
    pattern_item_t<declaration_t>::get()
  }
};

}   // ast

}   // gliss
