#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"
#include "relational-expression.h"

/**
 * Patterns for equality_expression
 *
 * 1. relational_expression
 * 2. equality_expression EQ_OP relational_expression
 * 3. equality_expression NE_OP relational_expression
 */

namespace gliss {

namespace ast {

class relational_expression_t;

class equality_expression_t: public ast_t {

public:

  static constexpr int rules = 3;

  static constexpr int id = 229;

  virtual ~equality_expression_t() = default;

};  // equality_expression_t

class equality_expression_relational_expression_t: public equality_expression_t {

public:

  std::shared_ptr<relational_expression_t> relational_expression_0;

  equality_expression_relational_expression_t(
    std::shared_ptr<relational_expression_t> relational_expression_0_
  ): relational_expression_0(relational_expression_0_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 229;
  }

  static std::shared_ptr<equality_expression_relational_expression_t> make(
    std::shared_ptr<relational_expression_t> relational_expression_0_
  ) {
    return std::make_shared<equality_expression_relational_expression_t>(
      relational_expression_0_
    );
  }

};  // equality_expression_relational_expression_t

class equality_expression_equality_expression_eq_op_relational_expression_t: public equality_expression_t {

public:

  std::shared_ptr<equality_expression_t> equality_expression_0;

  std::shared_ptr<ast_token_t> eq_op_1;

  std::shared_ptr<relational_expression_t> relational_expression_2;

  equality_expression_equality_expression_eq_op_relational_expression_t(
    std::shared_ptr<equality_expression_t> equality_expression_0_,
    std::shared_ptr<ast_token_t> eq_op_1_,
    std::shared_ptr<relational_expression_t> relational_expression_2_
  ): equality_expression_0(equality_expression_0_),
     eq_op_1(eq_op_1_),
     relational_expression_2(relational_expression_2_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 229;
  }

  static std::shared_ptr<equality_expression_equality_expression_eq_op_relational_expression_t> make(
    std::shared_ptr<equality_expression_t> equality_expression_0_,
    std::shared_ptr<ast_token_t> EQ_OP_1_,
    std::shared_ptr<relational_expression_t> relational_expression_2_
  ) {
    return std::make_shared<equality_expression_equality_expression_eq_op_relational_expression_t>(
      equality_expression_0_,
      EQ_OP_1_,
      relational_expression_2_
    );
  }

};  // equality_expression_equality_expression_eq_op_relational_expression_t

class equality_expression_equality_expression_ne_op_relational_expression_t: public equality_expression_t {

public:

  std::shared_ptr<equality_expression_t> equality_expression_0;

  std::shared_ptr<ast_token_t> ne_op_1;

  std::shared_ptr<relational_expression_t> relational_expression_2;

  equality_expression_equality_expression_ne_op_relational_expression_t(
    std::shared_ptr<equality_expression_t> equality_expression_0_,
    std::shared_ptr<ast_token_t> ne_op_1_,
    std::shared_ptr<relational_expression_t> relational_expression_2_
  ): equality_expression_0(equality_expression_0_),
     ne_op_1(ne_op_1_),
     relational_expression_2(relational_expression_2_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 229;
  }

  static std::shared_ptr<equality_expression_equality_expression_ne_op_relational_expression_t> make(
    std::shared_ptr<equality_expression_t> equality_expression_0_,
    std::shared_ptr<ast_token_t> NE_OP_1_,
    std::shared_ptr<relational_expression_t> relational_expression_2_
  ) {
    return std::make_shared<equality_expression_equality_expression_ne_op_relational_expression_t>(
      equality_expression_0_,
      NE_OP_1_,
      relational_expression_2_
    );
  }

};  // equality_expression_equality_expression_ne_op_relational_expression_t

}   // ast

}   // gliss
