#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "relational-expression.h"


namespace gliss {

namespace ast {

class equality_expression_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  equality_expression_t(
    const relational_expression_t &
  );

  equality_expression_t(
    const equality_expression_t &,
    const token_t &,
    const relational_expression_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // equality_expression_t

const std::vector<std::vector<any_pattern_item_t>> equality_expression_t::patterns = {
  {
    pattern_item_t<relational_expression_t>::get()
  }, {
    pattern_item_t<equality_expression_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("EQ_OP")),
    pattern_item_t<relational_expression_t>::get()
  }, {
    pattern_item_t<equality_expression_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("NE_OP")),
    pattern_item_t<relational_expression_t>::get()
  }
};

}   // ast

}   // gliss
