#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "and-expression.h"


namespace gliss {

namespace ast {

class exclusive_or_expression_t: public ast_t {

public:

  using unique_pattern_t = std::shared_ptr<any_pattern_item_t>;

  using pattern_t = std::vector<unique_pattern_t>;

  static const std::vector<pattern_t> patterns;

  exclusive_or_expression_t(
    const and_expression_t &
  );

  exclusive_or_expression_t(
    const exclusive_or_expression_t &,
    const token_t &,
    const and_expression_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // exclusive_or_expression_t

const std::vector<exclusive_or_expression_t::pattern_t> exclusive_or_expression_t::patterns = {
  {
    pattern_item_t<and_expression_t>::get()
  }, {
    pattern_item_t<exclusive_or_expression_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("CARET")),
    pattern_item_t<and_expression_t>::get()
  }
};

}   // ast

}   // gliss
