#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "function-definition.h"
#include "declaration.h"

namespace gliss {

namespace ast {

class external_declaration_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  external_declaration_t(
    const function_definition_t &
  );

  external_declaration_t(
    const declaration_t &
  );

  external_declaration_t(
    const token_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // external_declaration_t

const std::vector<std::vector<any_pattern_item_t>> external_declaration_t::patterns = {
  {
    pattern_item_t<function_definition_t>::get()
  }, {
    pattern_item_t<declaration_t>::get()
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("SEMICOLON"))
  }
};

}   // ast

}   // gliss
