#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "conditionopt.h"
#include "expression.h"

namespace gliss {

namespace ast {

class for_rest_statement_t: public ast_t {

public:

  using unique_pattern_t = std::shared_ptr<any_pattern_item_t>;

  using pattern_t = std::vector<unique_pattern_t>;

  static const std::vector<pattern_t> patterns;

  for_rest_statement_t(
    const conditionopt_t &,
    const token_t &
  );

  for_rest_statement_t(
    const conditionopt_t &,
    const token_t &,
    const expression_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // for_rest_statement_t

const std::vector<for_rest_statement_t::pattern_t> for_rest_statement_t::patterns = {
  {
    pattern_item_t<conditionopt_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("SEMICOLON"))
  }, {
    pattern_item_t<conditionopt_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("SEMICOLON")),
    pattern_item_t<expression_t>::get()
  }
};

}   // ast

}   // gliss
