#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"
#include "function-declarator.h"

/**
 * Patterns for function_prototype
 *
 * 1. function_declarator RIGHT_PAREN
 */

namespace gliss {

namespace ast {

class function_declarator_t;

class function_prototype_t: public ast_t {

public:

  static constexpr int rules = 1;

  static constexpr int id = 243;

  virtual ~function_prototype_t() = default;

};  // function_prototype_t

class function_prototype_function_declarator_right_paren_t: public function_prototype_t {

public:

  std::shared_ptr<function_declarator_t> function_declarator_0;

  std::shared_ptr<ast_token_t> right_paren_1;

  function_prototype_function_declarator_right_paren_t(
    std::shared_ptr<function_declarator_t> function_declarator_0_,
    std::shared_ptr<ast_token_t> right_paren_1_
  ): function_declarator_0(function_declarator_0_),
     right_paren_1(right_paren_1_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 243;
  }

  static std::shared_ptr<function_prototype_function_declarator_right_paren_t> make(
    std::shared_ptr<function_declarator_t> function_declarator_0_,
    std::shared_ptr<ast_token_t> RIGHT_PAREN_1_
  ) {
    return std::make_shared<function_prototype_function_declarator_right_paren_t>(
      function_declarator_0_,
      RIGHT_PAREN_1_
    );
  }

};  // function_prototype_function_declarator_right_paren_t

}   // ast

}   // gliss
