#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"
#include "function-declarator.h"

/**
 * Patterns for function_prototype
 *
 * 1. function_declarator RIGHT_PAREN
 */

namespace gliss {

namespace ast {

class function_declarator_t;

class function_prototype_t: public ast_t {

public:

  static constexpr int rules = 1;

  static constexpr int id = 242;

  virtual ~function_prototype_t() = default;

};  // function_prototype_t

class function_prototype_function_declarator_right_paren_t: public function_prototype_t {

public:

  std::unique_ptr<function_declarator_t> function_declarator_0;

  std::unique_ptr<token_t> right_paren_1;

  function_prototype_function_declarator_right_paren_t(
    std::unique_ptr<function_declarator_t> &&function_declarator_0_,
    std::unique_ptr<token_t> &&right_paren_1_
  ): function_declarator_0(std::move(function_declarator_0_)),
     right_paren_1(std::move(right_paren_1_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  static std::unique_ptr<function_prototype_function_declarator_right_paren_t> make(
    std::unique_ptr<function_declarator_t> &&function_declarator_0_,
    const token_t *RIGHT_PAREN_1_
  ) {
    return std::make_unique<function_prototype_function_declarator_right_paren_t>(
      std::move(function_declarator_0_),
      std::make_unique<token_t>(*RIGHT_PAREN_1_)
    );
  }

};  // function_prototype_function_declarator_right_paren_t

}   // ast

}   // gliss
