#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"
#include "function-call-header.h"
#include "assignment-expression.h"

/**
 * Patterns for function_call_header_with_parameters
 *
 * 1. function_call_header assignment_expression
 * 2. function_call_header_with_parameters COMMA assignment_expression
 */

namespace gliss {

namespace ast {

class function_call_header_t;
class assignment_expression_t;

class function_call_header_with_parameters_t: public ast_t {

public:

  static constexpr int rules = 2;

  static constexpr int id = 219;

  virtual ~function_call_header_with_parameters_t() = default;

};  // function_call_header_with_parameters_t

class function_call_header_with_parameters_function_call_header_assignment_expression_t: public function_call_header_with_parameters_t {

public:

  std::unique_ptr<function_call_header_t> function_call_header_0;

  std::unique_ptr<assignment_expression_t> assignment_expression_1;

  function_call_header_with_parameters_function_call_header_assignment_expression_t(
    std::unique_ptr<function_call_header_t> &&function_call_header_0_,
    std::unique_ptr<assignment_expression_t> &&assignment_expression_1_
  ): function_call_header_0(std::move(function_call_header_0_)),
     assignment_expression_1(std::move(assignment_expression_1_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  static std::unique_ptr<function_call_header_with_parameters_function_call_header_assignment_expression_t> make(
    std::unique_ptr<function_call_header_t> &&function_call_header_0_,
    std::unique_ptr<assignment_expression_t> &&assignment_expression_1_
  ) {
    return std::make_unique<function_call_header_with_parameters_function_call_header_assignment_expression_t>(
      std::move(function_call_header_0_),
      std::move(assignment_expression_1_)
    );
  }

};  // function_call_header_with_parameters_function_call_header_assignment_expression_t

class function_call_header_with_parameters_function_call_header_with_parameters_comma_assignment_expression_t: public function_call_header_with_parameters_t {

public:

  std::unique_ptr<function_call_header_with_parameters_t> function_call_header_with_parameters_0;

  std::unique_ptr<token_t> comma_1;

  std::unique_ptr<assignment_expression_t> assignment_expression_2;

  function_call_header_with_parameters_function_call_header_with_parameters_comma_assignment_expression_t(
    std::unique_ptr<function_call_header_with_parameters_t> &&function_call_header_with_parameters_0_,
    std::unique_ptr<token_t> &&comma_1_,
    std::unique_ptr<assignment_expression_t> &&assignment_expression_2_
  ): function_call_header_with_parameters_0(std::move(function_call_header_with_parameters_0_)),
     comma_1(std::move(comma_1_)),
     assignment_expression_2(std::move(assignment_expression_2_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  static std::unique_ptr<function_call_header_with_parameters_function_call_header_with_parameters_comma_assignment_expression_t> make(
    std::unique_ptr<function_call_header_with_parameters_t> &&function_call_header_with_parameters_0_,
    const token_t *COMMA_1_,
    std::unique_ptr<assignment_expression_t> &&assignment_expression_2_
  ) {
    return std::make_unique<function_call_header_with_parameters_function_call_header_with_parameters_comma_assignment_expression_t>(
      std::move(function_call_header_with_parameters_0_),
      std::make_unique<token_t>(*COMMA_1_),
      std::move(assignment_expression_2_)
    );
  }

};  // function_call_header_with_parameters_function_call_header_with_parameters_comma_assignment_expression_t

}   // ast

}   // gliss
