#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "function-prototype.h"
#include "compound-statement-no-new-scope.h"

namespace gliss {

namespace ast {

class function_definition_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  function_definition_t(
    const function_prototype_t &,
    const compound_statement_no_new_scope_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // function_definition_t

const std::vector<std::vector<any_pattern_item_t>> function_definition_t::patterns = {
  {
    pattern_item_t<function_prototype_t>::get(),
    pattern_item_t<compound_statement_no_new_scope_t>::get()
  }
};

}   // ast

}   // gliss
