#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"
#include "fully-specified-type.h"

/**
 * Patterns for function_header
 *
 * 1. fully_specified_type IDENTIFIER LEFT_PAREN
 */

namespace gliss {

namespace ast {

class fully_specified_type_t;

class function_header_t: public ast_t {

public:

  static constexpr int rules = 1;

  static constexpr int id = 246;

  virtual ~function_header_t() = default;

};  // function_header_t

class function_header_fully_specified_type_identifier_left_paren_t: public function_header_t {

public:

  std::shared_ptr<fully_specified_type_t> fully_specified_type_0;

  std::shared_ptr<ast_token_t> identifier_1;

  std::shared_ptr<ast_token_t> left_paren_2;

  function_header_fully_specified_type_identifier_left_paren_t(
    std::shared_ptr<fully_specified_type_t> fully_specified_type_0_,
    std::shared_ptr<ast_token_t> identifier_1_,
    std::shared_ptr<ast_token_t> left_paren_2_
  ): fully_specified_type_0(fully_specified_type_0_),
     identifier_1(identifier_1_),
     left_paren_2(left_paren_2_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 246;
  }

  static std::shared_ptr<function_header_fully_specified_type_identifier_left_paren_t> make(
    std::shared_ptr<fully_specified_type_t> fully_specified_type_0_,
    std::shared_ptr<ast_token_t> IDENTIFIER_1_,
    std::shared_ptr<ast_token_t> LEFT_PAREN_2_
  ) {
    return std::make_shared<function_header_fully_specified_type_identifier_left_paren_t>(
      fully_specified_type_0_,
      IDENTIFIER_1_,
      LEFT_PAREN_2_
    );
  }

};  // function_header_fully_specified_type_identifier_left_paren_t

}   // ast

}   // gliss
