#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "function-call-or-method.h"

namespace gliss {

namespace ast {

class function_call_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  function_call_t(
    const function_call_or_method_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // function_call_t

const std::vector<std::vector<any_pattern_item_t>> function_call_t::patterns = {
  {
    pattern_item_t<function_call_or_method_t>::get()
  }
};

}   // ast

}   // gliss
