#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"
#include "function-identifier.h"

/**
 * Patterns for function_call_header
 *
 * 1. function_identifier LEFT_PAREN
 */

namespace gliss {

namespace ast {

class function_identifier_t;

class function_call_header_t: public ast_t {

public:

  static constexpr int rules = 1;

  static constexpr int id = 220;

  virtual ~function_call_header_t() = default;

};  // function_call_header_t

class function_call_header_function_identifier_left_paren_t: public function_call_header_t {

public:

  std::unique_ptr<function_identifier_t> function_identifier_0;

  std::unique_ptr<token_t> left_paren_1;

  function_call_header_function_identifier_left_paren_t(
    std::unique_ptr<function_identifier_t> &&function_identifier_0_,
    std::unique_ptr<token_t> &&left_paren_1_
  ): function_identifier_0(std::move(function_identifier_0_)),
     left_paren_1(std::move(left_paren_1_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  static std::unique_ptr<function_call_header_function_identifier_left_paren_t> make(
    std::unique_ptr<function_identifier_t> &&function_identifier_0_,
    const token_t *LEFT_PAREN_1_
  ) {
    return std::make_unique<function_call_header_function_identifier_left_paren_t>(
      std::move(function_identifier_0_),
      std::make_unique<token_t>(*LEFT_PAREN_1_)
    );
  }

};  // function_call_header_function_identifier_left_paren_t

}   // ast

}   // gliss
