#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"
#include "function-call-header.h"

/**
 * Patterns for function_call_header_no_parameters
 *
 * 1. function_call_header VOID
 * 2. function_call_header
 */

namespace gliss {

namespace ast {

class function_call_header_t;

class function_call_header_no_parameters_t: public ast_t {

public:

  static constexpr int num_types = 2;

  virtual ~function_call_header_no_parameters_t() = default;

};  // function_call_header_no_parameters_t

class function_call_header_no_parameters_function_call_header_void_t: public function_call_header_no_parameters_t {

public:

  std::unique_ptr<function_call_header_t> function_call_header_0;

  std::unique_ptr<token_t> void_1;

  function_call_header_no_parameters_function_call_header_void_t(
    std::unique_ptr<function_call_header_t> &&function_call_header_0_,
    std::unique_ptr<token_t> &&void_1_
  ): function_call_header_0(std::move(function_call_header_0_)),
     void_1(std::move(void_1_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  static std::unique_ptr<function_call_header_no_parameters_function_call_header_void_t> make(
    std::unique_ptr<function_call_header_t> &&function_call_header_0_,
    const token_t *VOID_1_
  ) {
    return std::make_unique<function_call_header_no_parameters_function_call_header_void_t>(
      std::move(function_call_header_0_),
      std::make_unique<token_t>(*VOID_1_)
    );
  }

};  // function_call_header_no_parameters_function_call_header_void_t

class function_call_header_no_parameters_function_call_header_t: public function_call_header_no_parameters_t {

public:

  std::unique_ptr<function_call_header_t> function_call_header_0;

  function_call_header_no_parameters_function_call_header_t(
    std::unique_ptr<function_call_header_t> &&function_call_header_0_
  ): function_call_header_0(std::move(function_call_header_0_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  static std::unique_ptr<function_call_header_no_parameters_function_call_header_t> make(
    std::unique_ptr<function_call_header_t> &&function_call_header_0_
  ) {
    return std::make_unique<function_call_header_no_parameters_function_call_header_t>(
      std::move(function_call_header_0_)
    );
  }

};  // function_call_header_no_parameters_function_call_header_t

}   // ast

}   // gliss
