#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"
#include "exclusive-or-expression.h"

/**
 * Patterns for inclusive_or_expression
 *
 * 1. exclusive_or_expression
 * 2. inclusive_or_expression VERTICAL_BAR exclusive_or_expression
 */

namespace gliss {

namespace ast {

class exclusive_or_expression_t;

class inclusive_or_expression_t: public ast_t {

public:

  static constexpr int rules = 2;

  static constexpr int id = 232;

  virtual ~inclusive_or_expression_t() = default;

};  // inclusive_or_expression_t

class inclusive_or_expression_exclusive_or_expression_t: public inclusive_or_expression_t {

public:

  std::shared_ptr<exclusive_or_expression_t> exclusive_or_expression_0;

  inclusive_or_expression_exclusive_or_expression_t(
    std::shared_ptr<exclusive_or_expression_t> exclusive_or_expression_0_
  ): exclusive_or_expression_0(exclusive_or_expression_0_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 232;
  }

  static std::shared_ptr<inclusive_or_expression_exclusive_or_expression_t> make(
    std::shared_ptr<exclusive_or_expression_t> exclusive_or_expression_0_
  ) {
    return std::make_shared<inclusive_or_expression_exclusive_or_expression_t>(
      exclusive_or_expression_0_
    );
  }

};  // inclusive_or_expression_exclusive_or_expression_t

class inclusive_or_expression_inclusive_or_expression_vertical_bar_exclusive_or_expression_t: public inclusive_or_expression_t {

public:

  std::shared_ptr<inclusive_or_expression_t> inclusive_or_expression_0;

  std::shared_ptr<ast_token_t> vertical_bar_1;

  std::shared_ptr<exclusive_or_expression_t> exclusive_or_expression_2;

  inclusive_or_expression_inclusive_or_expression_vertical_bar_exclusive_or_expression_t(
    std::shared_ptr<inclusive_or_expression_t> inclusive_or_expression_0_,
    std::shared_ptr<ast_token_t> vertical_bar_1_,
    std::shared_ptr<exclusive_or_expression_t> exclusive_or_expression_2_
  ): inclusive_or_expression_0(inclusive_or_expression_0_),
     vertical_bar_1(vertical_bar_1_),
     exclusive_or_expression_2(exclusive_or_expression_2_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 232;
  }

  static std::shared_ptr<inclusive_or_expression_inclusive_or_expression_vertical_bar_exclusive_or_expression_t> make(
    std::shared_ptr<inclusive_or_expression_t> inclusive_or_expression_0_,
    std::shared_ptr<ast_token_t> VERTICAL_BAR_1_,
    std::shared_ptr<exclusive_or_expression_t> exclusive_or_expression_2_
  ) {
    return std::make_shared<inclusive_or_expression_inclusive_or_expression_vertical_bar_exclusive_or_expression_t>(
      inclusive_or_expression_0_,
      VERTICAL_BAR_1_,
      exclusive_or_expression_2_
    );
  }

};  // inclusive_or_expression_inclusive_or_expression_vertical_bar_exclusive_or_expression_t

}   // ast

}   // gliss
