#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "exclusive-or-expression.h"


namespace gliss {

namespace ast {

class inclusive_or_expression_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  inclusive_or_expression_t(
    const exclusive_or_expression_t &
  );

  inclusive_or_expression_t(
    const inclusive_or_expression_t &,
    const token_t &,
    const exclusive_or_expression_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // inclusive_or_expression_t

const std::vector<std::vector<any_pattern_item_t>> inclusive_or_expression_t::patterns = {
  {
    pattern_item_t<exclusive_or_expression_t>::get()
  }, {
    pattern_item_t<inclusive_or_expression_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("VERTICAL_BAR")),
    pattern_item_t<exclusive_or_expression_t>::get()
  }
};

}   // ast

}   // gliss
