#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "assignment-expression.h"
#include "initializer-list-body.h"
#include "initializer-list-body-trailing-comma.h"

namespace gliss {

namespace ast {

class initializer_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  initializer_t(
    const assignment_expression_t &
  );

  initializer_t(
    const initializer_list_body_t &
  );

  initializer_t(
    const initializer_list_body_trailing_comma_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // initializer_t

const std::vector<std::vector<any_pattern_item_t>> initializer_t::patterns = {
  {
    pattern_item_t<assignment_expression_t>::get()
  }, {
    pattern_item_t<initializer_list_body_t>::get()
  }, {
    pattern_item_t<initializer_list_body_trailing_comma_t>::get()
  }
};

}   // ast

}   // gliss
