#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "single-declaration.h"

#include "array-specifier.h"
#include "initializer.h"

namespace gliss {

namespace ast {

class init_declarator_list_t: public ast_t {

public:

  using unique_pattern_t = std::shared_ptr<any_pattern_item_t>;

  using pattern_t = std::vector<unique_pattern_t>;

  static const std::vector<pattern_t> patterns;

  init_declarator_list_t(
    const single_declaration_t &
  );

  init_declarator_list_t(
    const init_declarator_list_t &,
    const token_t &,
    const token_t &
  );

  init_declarator_list_t(
    const init_declarator_list_t &,
    const token_t &,
    const token_t &,
    const array_specifier_t &
  );

  init_declarator_list_t(
    const init_declarator_list_t &,
    const token_t &,
    const token_t &,
    const array_specifier_t &,
    const token_t &,
    const initializer_t &
  );

  init_declarator_list_t(
    const init_declarator_list_t &,
    const token_t &,
    const token_t &,
    const token_t &,
    const initializer_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // init_declarator_list_t

const std::vector<init_declarator_list_t::pattern_t> init_declarator_list_t::patterns = {
  {
    pattern_item_t<single_declaration_t>::get()
  }, {
    pattern_item_t<init_declarator_list_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("COMMA")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER"))
  }, {
    pattern_item_t<init_declarator_list_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("COMMA")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER")),
    pattern_item_t<array_specifier_t>::get()
  }, {
    pattern_item_t<init_declarator_list_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("COMMA")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER")),
    pattern_item_t<array_specifier_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("EQUAL")),
    pattern_item_t<initializer_t>::get()
  }, {
    pattern_item_t<init_declarator_list_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("COMMA")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("EQUAL")),
    pattern_item_t<initializer_t>::get()
  }
};

}   // ast

}   // gliss
