#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "single-declaration.h"

#include "init-declarator-list-array.h"
#include "init-declarator-list-array-initializer.h"
#include "init-declarator-list-initializer.h"

namespace gliss {

namespace ast {

class init_declarator_list_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  init_declarator_list_t(
    const single_declaration_t &
  );

  init_declarator_list_t(
    const init_declarator_list_t &,
    const token_t &,
    const token_t &
  );

  init_declarator_list_t(
    const init_declarator_list_array_t &
  );

  init_declarator_list_t(
    const init_declarator_list_array_initializer_t &
  );

  init_declarator_list_t(
    const init_declarator_list_initializer_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // init_declarator_list_t

const std::vector<std::vector<any_pattern_item_t>> init_declarator_list_t::patterns = {
  {
    pattern_item_t<single_declaration_t>::get()
  }, {
    pattern_item_t<init_declarator_list_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("COMMA")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER"))
  }, {
    pattern_item_t<init_declarator_list_array_t>::get()
  }, {
    pattern_item_t<init_declarator_list_array_initializer_t>::get()
  }, {
    pattern_item_t<init_declarator_list_initializer_t>::get()
  }
};

}   // ast

}   // gliss
