#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"
#include "expression.h"

/**
 * Patterns for integer_expression
 *
 * 1. expression
 */

namespace gliss {

namespace ast {

class expression_t;

class integer_expression_t: public ast_t {

public:

  static constexpr int rules = 1;

  static constexpr int id = 215;

  virtual ~integer_expression_t() = default;

};  // integer_expression_t

class integer_expression_expression_t: public integer_expression_t {

public:

  std::shared_ptr<expression_t> expression_0;

  integer_expression_expression_t(
    std::shared_ptr<expression_t> expression_0_
  ): expression_0(expression_0_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 215;
  }

  static std::shared_ptr<integer_expression_expression_t> make(
    std::shared_ptr<expression_t> expression_0_
  ) {
    return std::make_shared<integer_expression_expression_t>(
      expression_0_
    );
  }

};  // integer_expression_expression_t

}   // ast

}   // gliss
