#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "expression.h"

namespace gliss {

namespace ast {

class expression_t;

class integer_expression_t: public ast_t {

public:

  static constexpr int num_types = 1;

  template <int n, typename = void>
  struct pattern;

  template<int n>
  struct pattern<n, typename std::enable_if<n == 0>::type> {
    using type = integer_expression_expression_t;
    static std::vector<std::shared_ptr<any_pattern_item_t>> list;
  };

  virtual ~integer_expression_t() = default;

};  // integer_expression_t


class integer_expression_expression_t: public integer_expression_t {

public:

  std::unique_ptr<expression_t> expression_0;

  integer_expression_expression_t(
    std::unique_ptr<expression_t> &&expression_0_
  ): expression_0(std::move(expression_0_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // integer_expression_expression_t
  

template <>
std::vector<std::shared_ptr<any_pattern_item_t>> integer_expression_t::pattern<0>::list = {
  pattern_item_t<expression_t>::get()
};

}   // ast

}   // gliss
