#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"

namespace gliss {

namespace ast {

class invariant_qualifier_t: public ast_t {

public:

  static constexpr int num_types = 1;

  template <int n, typename = void>
  struct pattern;

  template<int n>
  struct pattern<n, typename std::enable_if<n == 0>::type> {
    using type = invariant_qualifier_invariant_t;
    static std::vector<std::shared_ptr<any_pattern_item_t>> list;
  };

  virtual ~invariant_qualifier_t() = default;

};  // invariant_qualifier_t

class invariant_qualifier_invariant_t: public invariant_qualifier_t {

public:

  std::unique_ptr<token_t> invariant_0;

  invariant_qualifier_invariant_t(
    std::unique_ptr<token_t> &&invariant_0_
  ): invariant_0(std::move(invariant_0_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // invariant_qualifier_invariant_t

template <>
std::vector<std::shared_ptr<any_pattern_item_t>> invariant_qualifier_t::pattern<0>::list = {
  pattern_item_t<token_t>::get(token_t::uppercase_to_kind("INVARIANT"))
};

}   // ast

}   // gliss
