#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"


namespace gliss {

namespace ast {

class invariant_qualifier_t: public ast_t {

public:

  using unique_pattern_t = std::shared_ptr<any_pattern_item_t>;

  using pattern_t = std::vector<unique_pattern_t>;

  static const std::vector<pattern_t> patterns;

  invariant_qualifier_t(
    const token_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // invariant_qualifier_t

const std::vector<invariant_qualifier_t::pattern_t> invariant_qualifier_t::patterns = {
  {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("INVARIANT"))
  }
};

}   // ast

}   // gliss
