#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"


namespace gliss {

namespace ast {

class jump_statement_break_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  jump_statement_break_t(
    const token_t &,
    const token_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // jump_statement_break_t

const std::vector<std::vector<any_pattern_item_t>> jump_statement_break_t::patterns = {
  {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("BREAK")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("SEMICOLON"))
  }
};

}   // ast

}   // gliss
