#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "expression.h"

namespace gliss {

namespace ast {

class jump_statement_t: public ast_t {

public:

  using unique_pattern_t = std::shared_ptr<any_pattern_item_t>;

  using pattern_t = std::vector<unique_pattern_t>;

  static const std::vector<pattern_t> patterns;

  jump_statement_t(
    const token_t &,
    const token_t &
  );

  jump_statement_t(
    const token_t &,
    const expression_t &,
    const token_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // jump_statement_t

const std::vector<jump_statement_t::pattern_t> jump_statement_t::patterns = {
  {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("CONTINUE")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("SEMICOLON"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("BREAK")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("SEMICOLON"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("RETURN")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("SEMICOLON"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("RETURN")),
    pattern_item_t<expression_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("SEMICOLON"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("DISCARD")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("SEMICOLON"))
  }
};

}   // ast

}   // gliss
