#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "constant-expression.h"

namespace gliss {

namespace ast {

class layout_qualifier_id_equal_constant_expression_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  layout_qualifier_id_equal_constant_expression_t(
    const token_t &,
    const token_t &,
    const constant_expression_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // layout_qualifier_id_equal_constant_expression_t

const std::vector<std::vector<any_pattern_item_t>> layout_qualifier_id_equal_constant_expression_t::patterns = {
  {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("EQUAL")),
    pattern_item_t<constant_expression_t>::get()
  }
};

}   // ast

}   // gliss
