#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "layout-qualifier-id-list.h"

namespace gliss {

namespace ast {

class layout_qualifier_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  layout_qualifier_t(
    const token_t &,
    const token_t &,
    const layout_qualifier_id_list_t &,
    const token_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // layout_qualifier_t

const std::vector<std::vector<any_pattern_item_t>> layout_qualifier_t::patterns = {
  {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("LAYOUT")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("LEFT_PAREN")),
    pattern_item_t<layout_qualifier_id_list_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("RIGHT_PAREN"))
  }
};

}   // ast

}   // gliss
