#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"
#include "logical-xor-expression.h"

/**
 * Patterns for logical_or_expression
 *
 * 1. logical_xor_expression
 * 2. logical_or_expression OR_OP logical_xor_expression
 */

namespace gliss {

namespace ast {

class logical_xor_expression_t;

class logical_or_expression_t: public ast_t {

public:

  static constexpr int rules = 2;

  static constexpr int id = 235;

  virtual ~logical_or_expression_t() = default;

};  // logical_or_expression_t

class logical_or_expression_logical_xor_expression_t: public logical_or_expression_t {

public:

  std::shared_ptr<logical_xor_expression_t> logical_xor_expression_0;

  logical_or_expression_logical_xor_expression_t(
    std::shared_ptr<logical_xor_expression_t> logical_xor_expression_0_
  ): logical_xor_expression_0(logical_xor_expression_0_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 235;
  }

  static std::shared_ptr<logical_or_expression_logical_xor_expression_t> make(
    std::shared_ptr<logical_xor_expression_t> logical_xor_expression_0_
  ) {
    return std::make_shared<logical_or_expression_logical_xor_expression_t>(
      logical_xor_expression_0_
    );
  }

};  // logical_or_expression_logical_xor_expression_t

class logical_or_expression_logical_or_expression_or_op_logical_xor_expression_t: public logical_or_expression_t {

public:

  std::shared_ptr<logical_or_expression_t> logical_or_expression_0;

  std::shared_ptr<ast_token_t> or_op_1;

  std::shared_ptr<logical_xor_expression_t> logical_xor_expression_2;

  logical_or_expression_logical_or_expression_or_op_logical_xor_expression_t(
    std::shared_ptr<logical_or_expression_t> logical_or_expression_0_,
    std::shared_ptr<ast_token_t> or_op_1_,
    std::shared_ptr<logical_xor_expression_t> logical_xor_expression_2_
  ): logical_or_expression_0(logical_or_expression_0_),
     or_op_1(or_op_1_),
     logical_xor_expression_2(logical_xor_expression_2_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 235;
  }

  static std::shared_ptr<logical_or_expression_logical_or_expression_or_op_logical_xor_expression_t> make(
    std::shared_ptr<logical_or_expression_t> logical_or_expression_0_,
    std::shared_ptr<ast_token_t> OR_OP_1_,
    std::shared_ptr<logical_xor_expression_t> logical_xor_expression_2_
  ) {
    return std::make_shared<logical_or_expression_logical_or_expression_or_op_logical_xor_expression_t>(
      logical_or_expression_0_,
      OR_OP_1_,
      logical_xor_expression_2_
    );
  }

};  // logical_or_expression_logical_or_expression_or_op_logical_xor_expression_t

}   // ast

}   // gliss
