#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"
#include "logical-and-expression.h"

namespace gliss {

namespace ast {

class logical_and_expression_t;

class logical_xor_expression_t: public ast_t {

public:

  static constexpr int num_types = 2;

  template <int n, typename = void>
  struct pattern;

  template<int n>
  struct pattern<n, typename std::enable_if<n == 0>::type> {
    using type = logical_xor_expression_logical_and_expression_t;
    static std::vector<std::shared_ptr<any_pattern_item_t>> list;
  };

  template<int n>
  struct pattern<n, typename std::enable_if<n == 1>::type> {
    using type = logical_xor_expression_logical_xor_expression_xor_op_logical_and_expression_t;
    static std::vector<std::shared_ptr<any_pattern_item_t>> list;
  };

  virtual ~logical_xor_expression_t() = default;

};  // logical_xor_expression_t

class logical_xor_expression_logical_and_expression_t: public logical_xor_expression_t {

public:

  std::unique_ptr<logical_and_expression_t> logical_and_expression_0;

  logical_xor_expression_logical_and_expression_t(
    std::unique_ptr<logical_and_expression_t> &&logical_and_expression_0_
  ): logical_and_expression_0(std::move(logical_and_expression_0_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // logical_xor_expression_logical_and_expression_t

class logical_xor_expression_logical_xor_expression_xor_op_logical_and_expression_t: public logical_xor_expression_t {

public:

  std::unique_ptr<logical_xor_expression_t> logical_xor_expression_0;

  std::unique_ptr<token_t> xor_op_1;

  std::unique_ptr<logical_and_expression_t> logical_and_expression_2;

  logical_xor_expression_logical_xor_expression_xor_op_logical_and_expression_t(
    std::unique_ptr<logical_xor_expression_t> &&logical_xor_expression_0_,
    std::unique_ptr<token_t> &&xor_op_1_,
    std::unique_ptr<logical_and_expression_t> &&logical_and_expression_2_
  ): logical_xor_expression_0(std::move(logical_xor_expression_0_)),
     xor_op_1(std::move(xor_op_1_)),
     logical_and_expression_2(std::move(logical_and_expression_2_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // logical_xor_expression_logical_xor_expression_xor_op_logical_and_expression_t

template <>
std::vector<std::shared_ptr<any_pattern_item_t>> logical_xor_expression_t::pattern<0>::list = {
  pattern_item_t<logical_and_expression_t>::get()
};

template <>
std::vector<std::shared_ptr<any_pattern_item_t>> logical_xor_expression_t::pattern<1>::list = {
  pattern_item_t<logical_xor_expression_t>::get(),
  pattern_item_t<token_t>::get(token_t::uppercase_to_kind("XOR_OP")),
  pattern_item_t<logical_and_expression_t>::get()
};

}   // ast

}   // gliss
