#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"


namespace gliss {

namespace ast {

class nothing_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // nothing_t

const std::vector<std::vector<any_pattern_item_t>> nothing_t::patterns = {
  
};

}   // ast

}   // gliss
