#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "type-specifier.h"

namespace gliss {

namespace ast {

class parameter_type_specifier_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  parameter_type_specifier_t(
    const type_specifier_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // parameter_type_specifier_t

const std::vector<std::vector<any_pattern_item_t>> parameter_type_specifier_t::patterns = {
  {
    pattern_item_t<type_specifier_t>::get()
  }
};

}   // ast

}   // gliss
