#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "type-qualifier.h"
#include "parameter-declarator.h"
#include "parameter-type-specifier.h"

namespace gliss {

namespace ast {

class parameter_declaration_t: public ast_t {

public:

  using unique_pattern_t = std::shared_ptr<any_pattern_item_t>;

  using pattern_t = std::vector<unique_pattern_t>;

  static const std::vector<pattern_t> patterns;

  parameter_declaration_t(
    const type_qualifier_t &,
    const parameter_declarator_t &
  );

  parameter_declaration_t(
    const parameter_declarator_t &
  );

  parameter_declaration_t(
    const type_qualifier_t &,
    const parameter_type_specifier_t &
  );

  parameter_declaration_t(
    const parameter_type_specifier_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // parameter_declaration_t

const std::vector<parameter_declaration_t::pattern_t> parameter_declaration_t::patterns = {
  {
    pattern_item_t<type_qualifier_t>::get(),
    pattern_item_t<parameter_declarator_t>::get()
  }, {
    pattern_item_t<parameter_declarator_t>::get()
  }, {
    pattern_item_t<type_qualifier_t>::get(),
    pattern_item_t<parameter_type_specifier_t>::get()
  }, {
    pattern_item_t<parameter_type_specifier_t>::get()
  }
};

}   // ast

}   // gliss
