#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "postfix-expression.h"

namespace gliss {

namespace ast {

class postfix_expression_increment_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  postfix_expression_increment_t(
    const postfix_expression_t &,
    const token_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // postfix_expression_increment_t

const std::vector<std::vector<any_pattern_item_t>> postfix_expression_increment_t::patterns = {
  {
    pattern_item_t<postfix_expression_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("INC_OP"))
  }
};

}   // ast

}   // gliss
