#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"

/**
 * Patterns for precise_qualifier
 *
 * 1. PRECISE
 */

namespace gliss {

namespace ast {

class precise_qualifier_t: public ast_t {

public:

  static constexpr int rules = 1;

  static constexpr int id = 257;

  virtual ~precise_qualifier_t() = default;

};  // precise_qualifier_t

class precise_qualifier_precise_t: public precise_qualifier_t {

public:

  std::unique_ptr<token_t> precise_0;

  precise_qualifier_precise_t(
    std::unique_ptr<token_t> &&precise_0_
  ): precise_0(std::move(precise_0_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  static std::unique_ptr<precise_qualifier_precise_t> make(
    const token_t *PRECISE_0_
  ) {
    return std::make_unique<precise_qualifier_precise_t>(
      std::make_unique<token_t>(*PRECISE_0_)
    );
  }

};  // precise_qualifier_precise_t

}   // ast

}   // gliss
