#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "shift-expression.h"


namespace gliss {

namespace ast {

class relational_expression_t: public ast_t {

public:

  using unique_pattern_t = std::shared_ptr<any_pattern_item_t>;

  using pattern_t = std::vector<unique_pattern_t>;

  static const std::vector<pattern_t> patterns;

  relational_expression_t(
    const shift_expression_t &
  );

  relational_expression_t(
    const relational_expression_t &,
    const token_t &,
    const shift_expression_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // relational_expression_t

const std::vector<relational_expression_t::pattern_t> relational_expression_t::patterns = {
  {
    pattern_item_t<shift_expression_t>::get()
  }, {
    pattern_item_t<relational_expression_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("LEFT_ANGLE")),
    pattern_item_t<shift_expression_t>::get()
  }, {
    pattern_item_t<relational_expression_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("RIGHT_ANGLE")),
    pattern_item_t<shift_expression_t>::get()
  }, {
    pattern_item_t<relational_expression_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("LE_OP")),
    pattern_item_t<shift_expression_t>::get()
  }, {
    pattern_item_t<relational_expression_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("GE_OP")),
    pattern_item_t<shift_expression_t>::get()
  }
};

}   // ast

}   // gliss
