#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"
#include "additive-expression.h"

/**
 * Patterns for shift_expression
 *
 * 1. additive_expression
 * 2. shift_expression LEFT_OP additive_expression
 * 3. shift_expression RIGHT_OP additive_expression
 */

namespace gliss {

namespace ast {

class additive_expression_t;

class shift_expression_t: public ast_t {

public:

  static constexpr int rules = 3;

  static constexpr int id = 227;

  virtual ~shift_expression_t() = default;

};  // shift_expression_t

class shift_expression_additive_expression_t: public shift_expression_t {

public:

  std::shared_ptr<additive_expression_t> additive_expression_0;

  shift_expression_additive_expression_t(
    std::shared_ptr<additive_expression_t> additive_expression_0_
  ): additive_expression_0(additive_expression_0_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 227;
  }

  static std::shared_ptr<shift_expression_additive_expression_t> make(
    std::shared_ptr<additive_expression_t> additive_expression_0_
  ) {
    return std::make_shared<shift_expression_additive_expression_t>(
      additive_expression_0_
    );
  }

};  // shift_expression_additive_expression_t

class shift_expression_shift_expression_left_op_additive_expression_t: public shift_expression_t {

public:

  std::shared_ptr<shift_expression_t> shift_expression_0;

  std::shared_ptr<ast_token_t> left_op_1;

  std::shared_ptr<additive_expression_t> additive_expression_2;

  shift_expression_shift_expression_left_op_additive_expression_t(
    std::shared_ptr<shift_expression_t> shift_expression_0_,
    std::shared_ptr<ast_token_t> left_op_1_,
    std::shared_ptr<additive_expression_t> additive_expression_2_
  ): shift_expression_0(shift_expression_0_),
     left_op_1(left_op_1_),
     additive_expression_2(additive_expression_2_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 227;
  }

  static std::shared_ptr<shift_expression_shift_expression_left_op_additive_expression_t> make(
    std::shared_ptr<shift_expression_t> shift_expression_0_,
    std::shared_ptr<ast_token_t> LEFT_OP_1_,
    std::shared_ptr<additive_expression_t> additive_expression_2_
  ) {
    return std::make_shared<shift_expression_shift_expression_left_op_additive_expression_t>(
      shift_expression_0_,
      LEFT_OP_1_,
      additive_expression_2_
    );
  }

};  // shift_expression_shift_expression_left_op_additive_expression_t

class shift_expression_shift_expression_right_op_additive_expression_t: public shift_expression_t {

public:

  std::shared_ptr<shift_expression_t> shift_expression_0;

  std::shared_ptr<ast_token_t> right_op_1;

  std::shared_ptr<additive_expression_t> additive_expression_2;

  shift_expression_shift_expression_right_op_additive_expression_t(
    std::shared_ptr<shift_expression_t> shift_expression_0_,
    std::shared_ptr<ast_token_t> right_op_1_,
    std::shared_ptr<additive_expression_t> additive_expression_2_
  ): shift_expression_0(shift_expression_0_),
     right_op_1(right_op_1_),
     additive_expression_2(additive_expression_2_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 227;
  }

  static std::shared_ptr<shift_expression_shift_expression_right_op_additive_expression_t> make(
    std::shared_ptr<shift_expression_t> shift_expression_0_,
    std::shared_ptr<ast_token_t> RIGHT_OP_1_,
    std::shared_ptr<additive_expression_t> additive_expression_2_
  ) {
    return std::make_shared<shift_expression_shift_expression_right_op_additive_expression_t>(
      shift_expression_0_,
      RIGHT_OP_1_,
      additive_expression_2_
    );
  }

};  // shift_expression_shift_expression_right_op_additive_expression_t

}   // ast

}   // gliss
