#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "fully-specified-type.h"
#include "array-specifier.h"
#include "initializer.h"

namespace gliss {

namespace ast {

class single_declaration_t: public ast_t {

public:

  using unique_pattern_t = std::shared_ptr<any_pattern_item_t>;

  using pattern_t = std::vector<unique_pattern_t>;

  static const std::vector<pattern_t> patterns;

  single_declaration_t(
    const fully_specified_type_t &
  );

  single_declaration_t(
    const fully_specified_type_t &,
    const token_t &
  );

  single_declaration_t(
    const fully_specified_type_t &,
    const token_t &,
    const array_specifier_t &
  );

  single_declaration_t(
    const fully_specified_type_t &,
    const token_t &,
    const array_specifier_t &,
    const token_t &,
    const initializer_t &
  );

  single_declaration_t(
    const fully_specified_type_t &,
    const token_t &,
    const token_t &,
    const initializer_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // single_declaration_t

const std::vector<single_declaration_t::pattern_t> single_declaration_t::patterns = {
  {
    pattern_item_t<fully_specified_type_t>::get()
  }, {
    pattern_item_t<fully_specified_type_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER"))
  }, {
    pattern_item_t<fully_specified_type_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER")),
    pattern_item_t<array_specifier_t>::get()
  }, {
    pattern_item_t<fully_specified_type_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER")),
    pattern_item_t<array_specifier_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("EQUAL")),
    pattern_item_t<initializer_t>::get()
  }, {
    pattern_item_t<fully_specified_type_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("EQUAL")),
    pattern_item_t<initializer_t>::get()
  }
};

}   // ast

}   // gliss
