#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"
#include "fully-specified-type.h"
#include "array-specifier.h"
#include "initializer.h"

/**
 * Patterns for single_declaration
 *
 * 1. fully_specified_type
 * 2. fully_specified_type IDENTIFIER
 * 3. fully_specified_type IDENTIFIER array_specifier
 * 4. fully_specified_type IDENTIFIER array_specifier EQUAL initializer
 * 5. fully_specified_type IDENTIFIER EQUAL initializer
 */

namespace gliss {

namespace ast {

class fully_specified_type_t;
class array_specifier_t;
class initializer_t;

class single_declaration_t: public ast_t {

public:

  static constexpr int rules = 5;

  static constexpr int id = 251;

  virtual ~single_declaration_t() = default;

};  // single_declaration_t

class single_declaration_fully_specified_type_t: public single_declaration_t {

public:

  std::shared_ptr<fully_specified_type_t> fully_specified_type_0;

  single_declaration_fully_specified_type_t(
    std::shared_ptr<fully_specified_type_t> fully_specified_type_0_
  ): fully_specified_type_0(fully_specified_type_0_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 251;
  }

  static std::shared_ptr<single_declaration_fully_specified_type_t> make(
    std::shared_ptr<fully_specified_type_t> fully_specified_type_0_
  ) {
    return std::make_shared<single_declaration_fully_specified_type_t>(
      fully_specified_type_0_
    );
  }

};  // single_declaration_fully_specified_type_t

class single_declaration_fully_specified_type_identifier_t: public single_declaration_t {

public:

  std::shared_ptr<fully_specified_type_t> fully_specified_type_0;

  std::shared_ptr<ast_token_t> identifier_1;

  single_declaration_fully_specified_type_identifier_t(
    std::shared_ptr<fully_specified_type_t> fully_specified_type_0_,
    std::shared_ptr<ast_token_t> identifier_1_
  ): fully_specified_type_0(fully_specified_type_0_),
     identifier_1(identifier_1_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 251;
  }

  static std::shared_ptr<single_declaration_fully_specified_type_identifier_t> make(
    std::shared_ptr<fully_specified_type_t> fully_specified_type_0_,
    std::shared_ptr<ast_token_t> IDENTIFIER_1_
  ) {
    return std::make_shared<single_declaration_fully_specified_type_identifier_t>(
      fully_specified_type_0_,
      IDENTIFIER_1_
    );
  }

};  // single_declaration_fully_specified_type_identifier_t

class single_declaration_fully_specified_type_identifier_array_specifier_t: public single_declaration_t {

public:

  std::shared_ptr<fully_specified_type_t> fully_specified_type_0;

  std::shared_ptr<ast_token_t> identifier_1;

  std::shared_ptr<array_specifier_t> array_specifier_2;

  single_declaration_fully_specified_type_identifier_array_specifier_t(
    std::shared_ptr<fully_specified_type_t> fully_specified_type_0_,
    std::shared_ptr<ast_token_t> identifier_1_,
    std::shared_ptr<array_specifier_t> array_specifier_2_
  ): fully_specified_type_0(fully_specified_type_0_),
     identifier_1(identifier_1_),
     array_specifier_2(array_specifier_2_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 251;
  }

  static std::shared_ptr<single_declaration_fully_specified_type_identifier_array_specifier_t> make(
    std::shared_ptr<fully_specified_type_t> fully_specified_type_0_,
    std::shared_ptr<ast_token_t> IDENTIFIER_1_,
    std::shared_ptr<array_specifier_t> array_specifier_2_
  ) {
    return std::make_shared<single_declaration_fully_specified_type_identifier_array_specifier_t>(
      fully_specified_type_0_,
      IDENTIFIER_1_,
      array_specifier_2_
    );
  }

};  // single_declaration_fully_specified_type_identifier_array_specifier_t

class single_declaration_fully_specified_type_identifier_array_specifier_equal_initializer_t: public single_declaration_t {

public:

  std::shared_ptr<fully_specified_type_t> fully_specified_type_0;

  std::shared_ptr<ast_token_t> identifier_1;

  std::shared_ptr<array_specifier_t> array_specifier_2;

  std::shared_ptr<ast_token_t> equal_3;

  std::shared_ptr<initializer_t> initializer_4;

  single_declaration_fully_specified_type_identifier_array_specifier_equal_initializer_t(
    std::shared_ptr<fully_specified_type_t> fully_specified_type_0_,
    std::shared_ptr<ast_token_t> identifier_1_,
    std::shared_ptr<array_specifier_t> array_specifier_2_,
    std::shared_ptr<ast_token_t> equal_3_,
    std::shared_ptr<initializer_t> initializer_4_
  ): fully_specified_type_0(fully_specified_type_0_),
     identifier_1(identifier_1_),
     array_specifier_2(array_specifier_2_),
     equal_3(equal_3_),
     initializer_4(initializer_4_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 251;
  }

  static std::shared_ptr<single_declaration_fully_specified_type_identifier_array_specifier_equal_initializer_t> make(
    std::shared_ptr<fully_specified_type_t> fully_specified_type_0_,
    std::shared_ptr<ast_token_t> IDENTIFIER_1_,
    std::shared_ptr<array_specifier_t> array_specifier_2_,
    std::shared_ptr<ast_token_t> EQUAL_3_,
    std::shared_ptr<initializer_t> initializer_4_
  ) {
    return std::make_shared<single_declaration_fully_specified_type_identifier_array_specifier_equal_initializer_t>(
      fully_specified_type_0_,
      IDENTIFIER_1_,
      array_specifier_2_,
      EQUAL_3_,
      initializer_4_
    );
  }

};  // single_declaration_fully_specified_type_identifier_array_specifier_equal_initializer_t

class single_declaration_fully_specified_type_identifier_equal_initializer_t: public single_declaration_t {

public:

  std::shared_ptr<fully_specified_type_t> fully_specified_type_0;

  std::shared_ptr<ast_token_t> identifier_1;

  std::shared_ptr<ast_token_t> equal_2;

  std::shared_ptr<initializer_t> initializer_3;

  single_declaration_fully_specified_type_identifier_equal_initializer_t(
    std::shared_ptr<fully_specified_type_t> fully_specified_type_0_,
    std::shared_ptr<ast_token_t> identifier_1_,
    std::shared_ptr<ast_token_t> equal_2_,
    std::shared_ptr<initializer_t> initializer_3_
  ): fully_specified_type_0(fully_specified_type_0_),
     identifier_1(identifier_1_),
     equal_2(equal_2_),
     initializer_3(initializer_3_) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

  virtual int get_id() const override {
    return 251;
  }

  static std::shared_ptr<single_declaration_fully_specified_type_identifier_equal_initializer_t> make(
    std::shared_ptr<fully_specified_type_t> fully_specified_type_0_,
    std::shared_ptr<ast_token_t> IDENTIFIER_1_,
    std::shared_ptr<ast_token_t> EQUAL_2_,
    std::shared_ptr<initializer_t> initializer_3_
  ) {
    return std::make_shared<single_declaration_fully_specified_type_identifier_equal_initializer_t>(
      fully_specified_type_0_,
      IDENTIFIER_1_,
      EQUAL_2_,
      initializer_3_
    );
  }

};  // single_declaration_fully_specified_type_identifier_equal_initializer_t

}   // ast

}   // gliss
