#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "statement.h"


namespace gliss {

namespace ast {

class statement_list_t: public ast_t {

public:

  using unique_pattern_t = std::shared_ptr<any_pattern_item_t>;

  using pattern_t = std::vector<unique_pattern_t>;

  static const std::vector<pattern_t> patterns;

  statement_list_t(
    const statement_t &
  );

  statement_list_t(
    const statement_list_t &,
    const statement_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // statement_list_t

const std::vector<statement_list_t::pattern_t> statement_list_t::patterns = {
  {
    pattern_item_t<statement_t>::get()
  }, {
    pattern_item_t<statement_list_t>::get(),
    pattern_item_t<statement_t>::get()
  }
};

}   // ast

}   // gliss
