#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "type-name-list.h"

namespace gliss {

namespace ast {

class storage_qualifier_t: public ast_t {

public:

  using unique_pattern_t = std::shared_ptr<any_pattern_item_t>;

  using pattern_t = std::vector<unique_pattern_t>;

  static const std::vector<pattern_t> patterns;

  storage_qualifier_t(
    const token_t &
  );

  storage_qualifier_t(
    const token_t &,
    const token_t &,
    const type_name_list_t &,
    const token_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // storage_qualifier_t

const std::vector<storage_qualifier_t::pattern_t> storage_qualifier_t::patterns = {
  {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("CONST"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("INOUT"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IN"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("OUT"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("CENTROID"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("PATCH"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("SAMPLE"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("UNIFORM"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("BUFFER"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("SHARED"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("COHERENT"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("VOLATILE"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("RESTRICT"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("READONLY"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("WRITEONLY"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("SUBROUTINE"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("SUBROUTINE")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("LEFT_PAREN")),
    pattern_item_t<type_name_list_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("RIGHT_PAREN"))
  }
};

}   // ast

}   // gliss
