#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "array-specifier.h"

namespace gliss {

namespace ast {

class struct_declarator_t: public ast_t {

public:

  using unique_pattern_t = std::shared_ptr<any_pattern_item_t>;

  using pattern_t = std::vector<unique_pattern_t>;

  static const std::vector<pattern_t> patterns;

  struct_declarator_t(
    const token_t &
  );

  struct_declarator_t(
    const token_t &,
    const array_specifier_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // struct_declarator_t

const std::vector<struct_declarator_t::pattern_t> struct_declarator_t::patterns = {
  {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER"))
  }, {
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER")),
    pattern_item_t<array_specifier_t>::get()
  }
};

}   // ast

}   // gliss
