#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "array-specifier.h"

namespace gliss {

namespace ast {

class array_specifier_t;

class struct_declarator_t: public ast_t {

public:

  static constexpr int num_types = 2;

  template <int n, typename = void>
  struct pattern;

  template<int n>
  struct pattern<n, typename std::enable_if<n == 0>::type> {
    using type = struct_declarator_identifier_t;
    static std::vector<std::shared_ptr<any_pattern_item_t>> list;
  };

  template<int n>
  struct pattern<n, typename std::enable_if<n == 1>::type> {
    using type = struct_declarator_identifier_array_specifier_t;
    static std::vector<std::shared_ptr<any_pattern_item_t>> list;
  };

  virtual ~struct_declarator_t() = default;

};  // struct_declarator_t


class struct_declarator_identifier_t: public struct_declarator_t {

public:

  std::unique_ptr<token_t> identifier_0;

  struct_declarator_identifier_t(
    std::unique_ptr<token_t> &&identifier_0_
  ): identifier_0(std::move(identifier_0_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // struct_declarator_identifier_t
  

class struct_declarator_identifier_array_specifier_t: public struct_declarator_t {

public:

  std::unique_ptr<token_t> identifier_0;

  std::unique_ptr<array_specifier_t> array_specifier_1;

  struct_declarator_identifier_array_specifier_t(
    std::unique_ptr<token_t> &&identifier_0_,
    std::unique_ptr<array_specifier_t> &&array_specifier_1_
  ): identifier_0(std::move(identifier_0_)),
     array_specifier_1(std::move(array_specifier_1_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // struct_declarator_identifier_array_specifier_t
  

template <>
std::vector<std::shared_ptr<any_pattern_item_t>> struct_declarator_t::pattern<0>::list = {
  pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER"))
};

template <>
std::vector<std::shared_ptr<any_pattern_item_t>> struct_declarator_t::pattern<1>::list = {
  pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER")),
  pattern_item_t<array_specifier_t>::get()
};

}   // ast

}   // gliss
