#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "struct-declarator.h"


namespace gliss {

namespace ast {

class struct_declarator_list_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  struct_declarator_list_t(
    const struct_declarator_t &
  );

  struct_declarator_list_t(
    const struct_declarator_list_t &,
    const token_t &,
    const struct_declarator_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // struct_declarator_list_t

const std::vector<std::vector<any_pattern_item_t>> struct_declarator_list_t::patterns = {
  {
    pattern_item_t<struct_declarator_t>::get()
  }, {
    pattern_item_t<struct_declarator_list_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("COMMA")),
    pattern_item_t<struct_declarator_t>::get()
  }
};

}   // ast

}   // gliss
