#pragma once

/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */

#include <vector>
#include "../ast.h"
#include "type-specifier-nonarray.h"
#include "array-specifier.h"

namespace gliss {

namespace ast {

class type_specifier_nonarray_t;
class array_specifier_t;

class type_specifier_t: public ast_t {

public:

  static constexpr int num_types = 2;

  template <int n, typename = void>
  struct pattern;

  template<int n>
  struct pattern<n, typename std::enable_if<n == 0>::type> {
    using type = type_specifier_type_specifier_nonarray_t;
    static std::vector<std::shared_ptr<any_pattern_item_t>> list;
  };

  template<int n>
  struct pattern<n, typename std::enable_if<n == 1>::type> {
    using type = type_specifier_type_specifier_nonarray_array_specifier_t;
    static std::vector<std::shared_ptr<any_pattern_item_t>> list;
  };

  virtual ~type_specifier_t() = default;

};  // type_specifier_t

class type_specifier_type_specifier_nonarray_t: public type_specifier_t {

public:

  std::unique_ptr<type_specifier_nonarray_t> type_specifier_nonarray_0;

  type_specifier_type_specifier_nonarray_t(
    std::unique_ptr<type_specifier_nonarray_t> &&type_specifier_nonarray_0_
  ): type_specifier_nonarray_0(std::move(type_specifier_nonarray_0_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // type_specifier_type_specifier_nonarray_t

class type_specifier_type_specifier_nonarray_array_specifier_t: public type_specifier_t {

public:

  std::unique_ptr<type_specifier_nonarray_t> type_specifier_nonarray_0;

  std::unique_ptr<array_specifier_t> array_specifier_1;

  type_specifier_type_specifier_nonarray_array_specifier_t(
    std::unique_ptr<type_specifier_nonarray_t> &&type_specifier_nonarray_0_,
    std::unique_ptr<array_specifier_t> &&array_specifier_1_
  ): type_specifier_nonarray_0(std::move(type_specifier_nonarray_0_)),
     array_specifier_1(std::move(array_specifier_1_)) {}

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // type_specifier_type_specifier_nonarray_array_specifier_t

template <>
std::vector<std::shared_ptr<any_pattern_item_t>> type_specifier_t::pattern<0>::list = {
  pattern_item_t<type_specifier_nonarray_t>::get()
};

template <>
std::vector<std::shared_ptr<any_pattern_item_t>> type_specifier_t::pattern<1>::list = {
  pattern_item_t<type_specifier_nonarray_t>::get(),
  pattern_item_t<array_specifier_t>::get()
};

}   // ast

}   // gliss
