#pragma once


/**
 * DO NOT MODIFY - AUTO GENERATED BY "../scripts/gen_cpp_node_constants.js"
 */
  

#include <vector>
#include "../ast.h"
#include "type-qualifier.h"
#include "struct-declaration-list.h"
#include "array-specifier.h"

namespace gliss {

namespace ast {

class type_qualifier_struct_declaration_list_identifier_array_t: public ast_t {

public:

  static const std::vector<std::vector<any_pattern_item_t>> patterns;

  type_qualifier_struct_declaration_list_identifier_array_t(
    const type_qualifier_t &,
    const token_t &,
    const token_t &,
    const struct_declaration_list_t &,
    const token_t &,
    const token_t &,
    const array_specifier_t &,
    const token_t &
  );

  virtual void accept(const visitor_t &visitor) const override {
    visitor(this);
  }

};  // type_qualifier_struct_declaration_list_identifier_array_t

const std::vector<std::vector<any_pattern_item_t>> type_qualifier_struct_declaration_list_identifier_array_t::patterns = {
  {
    pattern_item_t<type_qualifier_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("LEFT_BRACE")),
    pattern_item_t<struct_declaration_list_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("RIGHT_BRACE")),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("IDENTIFIER")),
    pattern_item_t<array_specifier_t>::get(),
    pattern_item_t<token_t>::get(token_t::uppercase_to_kind("SEMICOLON"))
  }
};

}   // ast

}   // gliss
