#pragma once

#include <xcbxx/events/button-press-event.h>
#include <xcbxx/events/circulate-notify-event.h>
#include <xcbxx/events/client-message-event.h>
#include <xcbxx/events/colormap-notify-event.h>
#include <xcbxx/events/configure-notify-event.h>
#include <xcbxx/events/configure-request-event.h>
#include <xcbxx/events/create-notify-event.h>
#include <xcbxx/events/destroy-notify-event.h>
#include <xcbxx/events/enter-notify-event.h>
#include <xcbxx/events/expose-event.h>
#include <xcbxx/events/focus-in-event.h>
#include <xcbxx/events/graphics-exposure-event.h>
#include <xcbxx/events/gravity-notify-event.h>
#include <xcbxx/events/key-press-event.h>
#include <xcbxx/events/keymap-notify-event.h>
#include <xcbxx/events/map-notify-event.h>
#include <xcbxx/events/map-request-event.h>
#include <xcbxx/events/mapping-notify-event.h>
#include <xcbxx/events/motion-notify-event.h>
#include <xcbxx/events/no-exposure-event.h>
#include <xcbxx/events/property-notify-event.h>
#include <xcbxx/events/reparent-notify-event.h>
#include <xcbxx/events/resize-request-event.h>
#include <xcbxx/events/selection-clear-event.h>
#include <xcbxx/events/selection-notify-event.h>
#include <xcbxx/events/selection-request-event.h>
#include <xcbxx/events/unmap-notify-event.h>
#include <xcbxx/events/visibility-notify-event.h>
